// defines for resource identifiers

#define IDS_GRUNTZ 0x8003
#define IDS_UNABLE_TO_CONTINUE_THE_GAME 0x8009
#define IDS_UNABLE_TO_INITIALIZE_THE_GAME 0x800A
#define IDS_GRUNTZ_CDROM_NOT_FOUND_RUN_IN_SPAWN_MODE 0x8021

#define IDC_CONFIG_ADVANCED_DISABLE_VIDEO 0x46C
#define IDC_CONFIG_ADVANCED_DISABLE_AUDIO 0x46D
#define IDC_CONFIG_ADVANCED_DISABLE_SOUND 0x46E
#define IDC_CONFIG_ADVANCED_DISABLE_MUSIC 0x46F
#define IDC_CONFIG_ADVANCED_DISABLE_MOVIE 0x470
#define IDC_CONFIG_ADVANCED_CANCEL 0x2
#define IDC_CONFIG_ADVANCED_OK 0x1
#define IDC_CONFIG_ADVANCED_DEFAULTS 0x426

#define IDC_ERROR_TEXT 0x40D
